### PR TITLE
decouple db existence check from metadata table creation

### LINKED ISSUE #42: Do not require CREATE SCHEMA privileges for --create-change-history-table when schema already exists
## Issue
When executing `schemachange` with the `--create-change-history-table` argument, the `CREATE SCHEMA` privilege is always required, even when the target schema for the change history table already exists.

## Context
Executing the `schemachange` command with the `--create-change-history-table` argument results in the tool executing a `CREATE SCHEMA IF NOT EXISTS` command to attempt creation of the schema where the change history table is meant to live. While this works for users having the `CREATE SCHEMA` privilege, it results in an error when a user having all the necessary privileges to execute DDL against the target schema (but lacking the `CREATE SCHEMA` privilege) executes this command. 

In order to successfully use the `schemachange` tool when the user lacks the `CREATE SCHEMA` privilege, manual intervention by the user is required to create the change history table by hand.

## Steps to Reproduce
Assumptions:
- The DBA user has `CREATE DATABASE` privileges on the Snowflake account.
- The Developer user does not have `CREATE DATABASE` or `CREATE SCHEMA` privileges.

Steps:
1. As the DBA user, create the `TEST_DB` database.
1. As the DBA user, create the `TEST_SCHEMA` schema in the `TEST_DB` database.
1. As the DBA user, assign full DDL privileges on the `TEST_DB.TEST_SCHEMA` schema to the Developer user, but do not assign `CREATE SCHEMA` privileges to the Developer user.
1. As the Developer user, execute the `schemachange` command with the `--create-change-history-table` and `--change-history-table TEST_DB.TEST_SCHEMA.CHANGE_HISTORY` arguments (with the account, user, role, warehouse, and database arguments set as appropriate).
### Expected Results
The `schemachange` command succeeds. The `CHANGE_HISTORY` table is created in the `TEST_DB.TEST_SCHEMA` schema, and any database change scripts in the current directory tree are executed.
### Current Results
The `schemachange` command attempts to create the `TEST_DB.TEST_SCHEMA` schema and fails due to the user lacking the `CREATE SCHEMA` privilege, despite the user having the ability to execute DDL in the target schema.

## Proposed Fix
Refactor the create change history table logic to decouple the check for the existence of the schema from the attempt to create that schema.

## Value
The `CREATE SCHEMA` privilege is no longer required to create the change history table when the schema already exists, enabling usage of this tool without manual intervention in scenarios where account privileges are more tightly controlled.

### PR DESCRIPTION
**Pull request by jm8451**
This pull request will decouple the schema existence check in the `create_change_history_table_if_missing` function from the attempt to create the schema. This will enable the tool to be used when the user executing the tool has the ability to execute DDL against an already existing target schema but does not have privileges to create a schema.

Fixes #42

### CODE REVIEW

**Comment by jm8451** [comment]
Hi @jamesweakley & @jeremiahhansen --

Sorry to bug you, but is there a chance one of you could have a look at this PR and provide feedback if there are questions or changes you'd like to see? It would be helpful to get this merged in so I (and others who might be following a similar pattern) don't have to create our change history tables by hand in order to use this tool.

Thanks!
-JM

**Comment by jamesweakley** [comment]
Sorry @jm8451, this slipped through my radar. Seems like a straightforward and uncontroversial change, will approve

**Comment by sfc-gh-jhansen** [comment]
Hey @jm8451 (and @jamesweakley), thanks so much for the contributions to schemachange, and I agree that this change seems helpful.

But it looks like we missed a few things here. In particular, we need to change the schemachange version # and add a corresponding entry to the CHANGELOG.md file. Can you please open a new PR with those changes? Once those are merged then I will create a new package in PyPI.

Thanks!

**Comment by jm8451** [comment]
Hi @sfc-gh-jhansen -- it looks like @jamesweakley bumped the version to 2.9.2 and placed an entry in CHANGELOG.md for the change when he merged the PR on 2021-06-11. (Thanks, James!)

Is there any further action required on my part?

**Comment by sfc-gh-jhansen** [comment]
Thanks @jm8451, I missed that as it was outside this PR and I just didn't bother to check. Thanks @jamesweakley for taking care of that.

Alright, just published 2.9.2 to PyPI. Thanks again for making schemachange better!

**Pull request merged**
