### PR TITLE
Add quotes around database and schema name

### PR DESCRIPTION
**Pull request by estheban**
For https://github.com/Snowflake-Labs/schemachange/issues/72

### CODE REVIEW

**Comment by LeoPastaBuddy** [comment]
This PR would be super useful for me as well, as it would allow us to adopt lower case database names. 
Any plans on when this could be merged to main?

**Comment by estheban** [comment]
Quick follow up, can we merge this ?

**Comment by sfc-gh-jhansen** [comment]
Hi there @estheban, thanks for the reminder, and sorry for the slow response here. I'm a bit hesitant to merge these changes. IMO, it's a best practice in general to avoid quoted identifiers. See the Snowflake [Identifier Requirements](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html) page for more details (particularly the quoted identifier sections/warnings).

As a result, I'm hesitant to make this the default for all users. I'd like to better understand if/how it will impact users. Maybe we add a corresponding flag to enable this behavior and leave it disabled by default?

**Comment by estheban** [comment]
Sure, a config flag is a good idea.  

Personally I moved away as for my use case, I have a lot of repetition to do and going with a coded approach was better suited for us.

**Pull request closed without merging**
