### PR TITLE
Log Current Session ID

### PR DESCRIPTION
**Pull request by opodoprigora**
Log Current Session ID

### CODE REVIEW

**Comment by opodoprigora** [comment]
@sfc-gh-twhite please take a look when ever you have a chance.

**Comment by sfc-gh-twhite** [comment]
Thank you for the PR!

I would opt to use the session_id that is available from the property of the Snowflake connection. For example, we can do this:

```py
import snowflake.connector

con = snowflake.connector.connect()

print(con.session_id)
```
I believe that avoids the extra query submission. :)

**Comment by opodoprigora** [comment]
@sfc-gh-twhite good call 💪 , updated.

**Comment by sfc-gh-twhite** [comment]
Awesome job! We're doing a good bit of overhauling from a maintenance perspective of this project, but hopefully we can get this one in soon.

**Pull request merged**
