### PR TITLE
feat: defer to SNOWFLAKE_TOKEN environment variable if set instead of fetching an Oauth token

### PR DESCRIPTION
**Pull request by zanebclark**
Addresses [Feature Request 290](https://github.com/Snowflake-Labs/schemachange/issues/290)

### CODE REVIEW

**Comment by zanebclark** [comment]
@sfc-gh-tmathew @jamesweakley @sfc-gh-jhansen, another one with test cases

**Review by sfc-gh-jhansen — APPROVED** [review]

**Comment by sfc-gh-jhansen** [comment]
Looks good, thanks! Please see my comments on https://github.com/Snowflake-Labs/schemachange/pull/285 about getting the tests to pass.

**Comment by zanebclark** [comment]
@sfc-gh-tmathew and @sfc-gh-jhansen, flagging a few 4.0.0 candidates.

**Comment by zanebclark** [comment]
Closing in favor of #298

**Pull request closed without merging**
