### PR TITLE
feat: code reorganization

### PR DESCRIPTION
**Pull request by zanebclark**
This is a resurrection of [PR 222](https://github.com/Snowflake-Labs/schemachange/pull/222) and [PR 275](https://github.com/Snowflake-Labs/schemachange/pull/275). This pull request contains a repo refactor with purposeful functionality changes. 
- Replace print statements and `if verbose` checks with a [structlog](https://www.structlog.org/en/stable/) logger and log levels.
- Removed SecretManager in favor of a structlog processor that implements similar logic. 
- Centralize config-related logic and input checking into a `Config` object. For example, there was logic for checking the validity of a directory and the presence of environment variables. Centralizing this logic is conceptually easier for me to wrap my head around and makes testing much easier. 
- Generally, moved a bunch of class definitions out of `cli.py` and into separate files
- Stored script details in a `Script` class to clarify the API
- Removed a bunch of credential-related logic from `SnowflakeClient` and created a `Credential` factory. 
- Generally expanded test case coverage.

### CODE REVIEW

**Comment by zanebclark** [comment]
@sfc-gh-tmathew , this is the code reorganization pull request you ask for as part of [275](https://github.com/Snowflake-Labs/schemachange/pull/275)

**Comment by zanebclark** [comment]
@MACKAT05 , fyi

**Comment by sanelson** [comment]
This is amazing work! I should have dug around in the old pull requests before submitting my own massive refactor pull request #282 a few weeks ago... If it will help this pull request get any traction, I'm happy to refactor all my changes on to these new changes proposed by @zanebclark . Seems like a really solid base to build off of. Nice work!

**Comment by jamesweakley** [comment]
This looks like a nice refactor to me, appreciate the contribution.

Since @sfc-gh-tmathew has alredy provided feedback on the original PR, I'll wait for his review. I've set a reminder to come back early next week and check that it's been reviewed.

Since this is the "no functionality changes" PR it should be straightforward enough to approve.

**Comment by zanebclark** [comment]
Thanks, @jamesweakley.  I'm standing on the shoulders of giants. Think about that next time you have back pain 😉

**Review by jamesweakley — APPROVED** [review]

**Comment by sfc-gh-jhansen** [comment]
Hey there @zanebclark, thank you for the refactor, I agree that it looks helpful!

I'll let @sfc-gh-tmathew chime in here, but it looks like a few tests still aren't passing. See this GitHub Actions run: https://github.com/Snowflake-Labs/schemachange/actions/runs/11330550805. Can you please help us sort these out so we can get this released as version 4.0?

**Pull request merged**
