### PR TITLE
Added Support for schema syncing via cli

### PR DESCRIPTION
**Pull request by yakshup**
Extending #180 with cli options and tracking in change history

### CODE REVIEW

**Comment by sfc-gh-tmathew** [comment]
@yakshup By adding the schema column without the altering the table structure will result in failure. This will also require documentation updates and ensure that existing users of schemachange do not loose the change history when upgrading to a release that includes this change. This cannot be accepted in its current state and needs more work.

**Comment by podung** [comment]
Sorry all - I didn't see this PR hanging off my original.  I finally have my original fully up to date and ready to commit, though I needed to open a new PR: #210 .

It has tests, documentation, cli support, and yml config support

**Comment by podung** [comment]
On the additional specific effort in #196, I'm not exactly clear what was being attempted.  @yakshup can you elaborate on what use case you were trying to support by wanting to track a schema column on the change history table?

**Comment by yakshup** [comment]
> On the additional specific effort in #196, I'm not exactly clear what was being attempted. @yakshup can you elaborate on what use case you were trying to support by wanting to track a schema column on the change history table?

@podung We had a requirement to track changes per schema on which changes are made. I believe this was something which was raised in #180.

**Comment by sfc-gh-tmathew** [comment]
Thank you for contributions but we will not be including this change to the schemachange feature.

**Pull request closed without merging**
